kind: pipeline
name: docs
type: docker
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: node:slim
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: build
        path: /drone/src/build
    commands:
      - npm i && npm run build
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: node_modules
    host:
      path: /root/node/docs/node_modules
  - name: build
    host:
      path: /root/nginx/www/docs
## drone 部署前端项目至nginx挂载目录